[Universal] - reduce size - removed nvidia, triton - Machine Learning Packages
devcontainers/images pull request #1014
Opened 2024-04-02 17:16 UTC by gauravsaini04

**Dev container name**: 

   * Universal

**Description**:

   * _Shrink size of the Universal Image_

*Changelog*:

   * Changed `install.sh` file in `local-features` - `Machine-learning-packages` such that `Torch` package wouldn't have GPU acceleration that'll be installed as default, so to avoid downloading and installing of big sized packages such as `nvidia` & `triton`

**Checklist**:

- [x] Checked that applied changes work as expected

2024-04-02 18:44 UTC, samruddhikhandale commented
Seems like tests did not run for this PR, closing and opening it.

2024-04-02 18:48 UTC, samruddhikhandale requested changes

2024-04-02 18:48 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip uninstall --yes torch
We can remove this as upstream won't install it.

2024-04-02 18:48 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    echo "Installing Torch..."
nit: Remove?

2024-04-02 18:48 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
I believe we still need to use `+cpu` suffix to install CPU variant? Something like `pip install torch==${VERSION}+cpu -f https://download.pytorch.org/whl/torch_stable.html`

2024-04-02 18:48 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
I need to chat with PMs before we make this decision of removing GPU support, I'll update shortly.

2024-04-02 20:39 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
Hmm.. Strange, it is still install cpu version as the image size has shrinked

2024-04-02 20:40 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
Ah, nevermind. You are using https://download.pytorch.org/whl/cpu/torch_stable.html 👍

2024-04-02 20:41 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
>      install_python_package "requests"
Let's update threshold to 10 GB 🎉 

https://github.com/devcontainers/images/blob/9c73c0491ea1db9d82b01075a99c00e88dee32f1/.github/workflows/smoke-universal.yaml#L29

2024-04-02 21:01 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
We can make torch CPU only provided we provide a notification to users which creates a codespace with GPU.

Can you add `onCreateCommand` to the [local ML](https://github.com/devcontainers/images/tree/d39040b437710e867ca4e155c30d6d8d47b3c62a/src/universal/.devcontainer/local-features/machine-learning-packages) Feature, which detects GPU (maybe with `lspci`) and appends warning to /workspaces/.codespaces/shared/first-run-notice.txt

2024-04-03 07:31 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip uninstall --yes torch
updated the code ! 👍🏻

2024-04-03 07:31 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    echo "Installing Torch..."
updated the code according to review  comments !

2024-04-03 07:32 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir torch -f https://download.pytorch.org/whl/cpu/torch_stable.html
Have updated code in installation file

2024-04-03 07:32 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
>      install_python_package "requests"
updated to 10

2024-04-03 22:15 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +        echo "GPU Detected. Installing Torch with GPU support."
This won't work as this script runs during building the image (which only runs in a CPU GH action)

Hence, you need to add similar logic to a `onCreateCommand`. Read more at https://containers.dev/implementors/json_reference/#lifecycle-scripts

![image](https://github.com/devcontainers/images/assets/24955913/5d634ace-bd67-4f13-8c0d-b02fd5f62756)

2024-04-07 21:42 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +        echo "GPU Detected. Installing Torch with GPU support."
I have added the above logic, though not able to solve this, that while `torch` is getting installed through the newly added `OnCreateCommand.sh` but it doesn't show in the dive of the formed image thus formed: 👇🏻
<img width="1633" alt="Screenshot 2024-04-08 at 3 03 09 AM" src="https://github.com/devcontainers/images/assets/147703805/cd67a553-6502-4db4-bd87-1d51b5f60335">

2024-04-08 22:44 UTC, samruddhikhandale requested changes

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +#!/bin/bash
Let's rename this file to `installTorchForGPU.sh`

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    echo "jq not found. Attempting to install...";
Let's remove the trailing `;` ?

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +    "onCreateCommand": "chmod +x ./.devcontainer/OnCreateCommand.sh; ./.devcontainer/OnCreateCommand.sh;",
Can we add this to https://github.com/devcontainers/images/blob/dba42b0eb5fed776e19fa0dc9f6c7ca0807ea56d/src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json ?

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +    "onCreateCommand": "chmod +x ./.devcontainer/OnCreateCommand.sh; ./.devcontainer/OnCreateCommand.sh;",
eg. https://github.com/devcontainers/features/blob/main/src/git-lfs/devcontainer-feature.json#L28

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> -    install_python_package "torch"
We want to continue installing `torch` (CPU only)

The `onCreateCommand` will only install torch-GPU if it detects GPU arch.

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +
Instead of creating this file here, can we do something like https://github.com/devcontainers/features/blob/main/src/git-lfs/install.sh#L212-L222

where it is creating a file within Feature's `install.sh`, which we won't have to `chmod` while executing in https://github.com/devcontainers/images/pull/1014/files#diff-0a764bd0944b79c46597d08357a72f308324874b8e25e7d46f302ecc0bc47bafR111

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    sudo apt-get update;
Post my previous comment, you don't have to use `sudo` as `install.sh` is run by root user

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +machine_learning_packages_key_value=$(echo "$json" | jq -r '.features | to_entries[] | select(.key == "./local-features/machine-learning-packages") | .value')
Why do we need this?

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    username_value=$(echo "$json" | jq -r '.features."./local-features/machine-learning-packages" // empty | .username // empty')
Username is always `codespace` for this image, safe to assume

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    sudo chmod -R 755 /var/lib/apt/lists
why do we need this?

2024-04-08 22:44 UTC, samruddhikhandale commented on src/universal/.devcontainer/OnCreateCommand.sh
> +        echo "No GPU Detected. Installing Torch with CPU support.";
With my previous comment, this won't be needed/

2024-04-09 03:06 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +        echo "GPU Detected. Installing Torch with GPU support."
yeah ! Got it. So, the implementation is correct ? right ?

2024-04-09 07:34 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +machine_learning_packages_key_value=$(echo "$json" | jq -r '.features | to_entries[] | select(.key == "./local-features/machine-learning-packages") | .value')
oh ok, thought to check whether machine-learning-packages is indeed getting installed by the customized universal image that the user might be using. Though, this is the default image that gets installed when user doesn't mention his own image for the devcontainer.

2024-04-09 07:35 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    username_value=$(echo "$json" | jq -r '.features."./local-features/machine-learning-packages" // empty | .username // empty')
ok

2024-04-09 07:37 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +        echo "No GPU Detected. Installing Torch with CPU support.";
ok 👍🏻

2024-04-09 09:41 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +        echo "GPU Detected. Installing Torch with GPU support."
Corrected based on further comments. Thanks for suggesting such a simple approach.

2024-04-09 09:41 UTC, gauravsaini04 commented on src/universal/.devcontainer/devcontainer.json
> +    "onCreateCommand": "chmod +x ./.devcontainer/OnCreateCommand.sh; ./.devcontainer/OnCreateCommand.sh;",
corrected ! Thanks !

2024-04-09 09:41 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    echo "jq not found. Attempting to install...";
corrected 👍🏻

2024-04-09 09:42 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +#!/bin/bash
Corrected the filename

2024-04-09 09:42 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> -    install_python_package "torch"
👍🏻

2024-04-09 09:43 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +
thanks, this approach made it all so simple !

2024-04-09 09:45 UTC, gauravsaini04 commented on src/universal/.devcontainer/OnCreateCommand.sh
> +    sudo apt-get update;
its simple and really great way to implement any such logic.. thanks a lot for sharing this..

2024-04-12 16:59 UTC, samruddhikhandale requested changes

2024-04-12 16:59 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +        // "./local-features/setup-user": "latest",
Looks like this was used for testing, remove the changes?

2024-04-12 16:59 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +        // "./local-features/setup-user"
Looks like this was used for testing, remove the changes?

2024-04-12 16:59 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    # install_python_package "scikit-learn"
Looks like this was used for testing, remove the changes?

2024-04-12 16:59 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "chmod 755 startContainer.sh; ./startContainer.sh;",
Why do we need `startContainer.sh`?  We can simply execute `usr/local/share/installTorchForGPU.sh` in here

2024-04-12 16:59 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +# set +x
Remove?

2024-04-16 10:44 UTC, gauravsaini04 commented on src/universal/.devcontainer/devcontainer.json
> +        // "./local-features/setup-user": "latest",
sorry about it. removed.

2024-04-16 10:44 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    # install_python_package "scikit-learn"
removed

2024-04-16 10:45 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "chmod 755 startContainer.sh; ./startContainer.sh;",
yes, earlier was facing some issues. But could simply run file from postCreateCommand hook.

2024-04-16 10:45 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +# set +x
removed.

2024-04-16 11:05 UTC, gauravsaini04 commented on src/universal/.devcontainer/devcontainer.json
> +        // "./local-features/setup-user"
done

2024-04-16 22:41 UTC, samruddhikhandale requested changes

2024-04-16 22:41 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    shift  # Remove the first argument (PACKAGE) from the list of arguments
why do we need to do this? why don't we accept `-f https://download.pytorch.org/whl/cpu/torch_stable.html` as a second arg?

2024-04-16 22:41 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "sudo chmod +x /usr/local/share/installTorchForGPU.sh; cd /usr/local/share/; ./installTorchForGPU.sh;",
> sudo chmod +x /usr/local/share/installTorchForGPU.sh;

Can we do this in src/universal/.devcontainer/local-features/machine-learning-packages/install.sh ?

2024-04-16 22:41 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    echo "GPU Not Detected. Torch without GPU Acceleration is already installed."
Let's remove this echo.

2024-04-16 22:41 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +echo -e "\nAttempting to install Torch with GPU Acceleration if NVIDIA GPU is available..\n"
Let's remove this echo.

2024-04-17 03:13 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    shift  # Remove the first argument (PACKAGE) from the list of arguments
corrected. thanks !

2024-04-17 03:13 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "sudo chmod +x /usr/local/share/installTorchForGPU.sh; cd /usr/local/share/; ./installTorchForGPU.sh;",
done

2024-04-17 03:13 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +echo -e "\nAttempting to install Torch with GPU Acceleration if NVIDIA GPU is available..\n"
done

2024-04-17 03:13 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    echo "GPU Not Detected. Torch without GPU Acceleration is already installed."
done

2024-04-22 22:54 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "cd /usr/local/share/; ./installTorchForGPU.sh;",
```suggestion
	"postCreateCommand": "./usr/local/share/installTorchForGPU.sh;",
```

2024-04-22 23:42 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/devcontainer-feature.json
> +	"postCreateCommand": "cd /usr/local/share/; ./installTorchForGPU.sh;",
done

2024-05-07 17:51 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    install_python_package "torch" -f https://download.pytorch.org/whl/cpu/torch_stable.html
Why is the size of the `universal` image still 14 GB? 
https://github.com/devcontainers/images/actions/runs/8989223630/job/24691847387?pr=1014#step:3:42649

2024-05-07 17:51 UTC, samruddhikhandale commented on .github/workflows/smoke-universal.yaml
> +        threshold: 10
The test failed, but it did not fail the action run. Can you fix this?
https://github.com/devcontainers/images/actions/runs/8989223630/job/24691847387?pr=1014#step:3:42673

2024-05-08 03:36 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    install_python_package "torch" -f https://download.pytorch.org/whl/cpu/torch_stable.html
because was not accepting all the arguments sent after torch, didn't change the installing fn accordingly, have pushed my changes now.

2024-05-08 11:07 UTC, gauravsaini04 commented on .github/workflows/smoke-universal.yaml
> +        threshold: 10
have written a script exiting codeline in check-image-size.sh, let me know if that's what was wanted

2024-05-08 18:26 UTC, samruddhikhandale requested changes

2024-05-08 18:26 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    fi
```suggestion
    sudo_if /usr/local/python/current/bin/python -m pip install --user --upgrade --no-cache-dir "$PACKAGE" "$OPTIONS"
```

2024-05-08 18:26 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    install_python_package "torch" -f https://download.pytorch.org/whl/cpu/torch_stable.html
```suggestion
    install_python_package "torch" "-f https://download.pytorch.org/whl/cpu/torch_stable.html"
```

Why don't we pass it as ^, then we can avoid using `shift`

2024-05-09 09:49 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    install_python_package "torch" -f https://download.pytorch.org/whl/cpu/torch_stable.html
sure done

2024-05-09 09:49 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    fi
done

2024-05-09 09:49 UTC, gauravsaini04 commented on src/universal/.devcontainer/local-features/machine-learning-packages/install.sh
> +    OPTIONS=$@
done

2024-05-09 23:38 UTC, samruddhikhandale approved these changes
This is a wonderful change, so good to see the `universal` image shrink from 14 GB to 9.8 GB 🎉

2024-05-09 23:38 UTC, merged