[Anaconda] - remove pinned packages as availabe versions from upstream greater than pinned
devcontainers/images pull request #1073
Opened 2024-05-22 06:30 UTC by gauravsaini04

**Dev container name**:
 
 * Anaconda
 
 **Description**:
 
 This PR removes a number of pinned packages as available packages from upstream have greater or equal versions for them.
 
 _Changelog_:
 
 * Updated `Dockerfile`
 * Updated tests
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-05-22 20:51 UTC, samruddhikhandale requested changes

2024-05-22 20:51 UTC, samruddhikhandale commented on src/anaconda/test-project/test.sh
> -checkPythonPackageVersion "cookiecutter" "2.1.1"
Can we keep the tests around? This way we can test if the removal is working, also would ensure that we don't install any previous version in future.

2024-05-22 23:31 UTC, gauravsaini04 commented on src/anaconda/test-project/test.sh
> -checkPythonPackageVersion "cookiecutter" "2.1.1"
sure reverted the test file changes..

2024-05-23 22:23 UTC, samruddhikhandale approved these changes
Nice 🧹

2024-05-23 22:23 UTC, merged