[Miniconda] - remove pinned packages - as higher versions availabe from upstream image
devcontainers/images pull request #1074
Opened 2024-05-22 06:53 UTC by gauravsaini04

**Dev container name**:
 
 * Miniconda
 
 **Description**:
 
 This PR removes a couple of pinned packages as similar available packages from upstream have greater version for them.
 
 _Changelog_:
 
 * Updated `Dockerfile`
 * Updated tests
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-05-22 20:51 UTC, samruddhikhandale requested changes

2024-05-22 20:51 UTC, samruddhikhandale commented on src/miniconda/test-project/test.sh
> -checkPythonPackageVersion "cryptography" "42.0.4"
Can we keep the tests around? This way we can test if the removal is working, also would ensure that we don't install any previous version in future.

2024-05-22 23:35 UTC, gauravsaini04 commented on src/miniconda/test-project/test.sh
> -checkPythonPackageVersion "cryptography" "42.0.4"
done

2024-05-23 22:25 UTC, samruddhikhandale approved these changes
🧹

2024-05-23 22:25 UTC, merged