[anaconda]-auto install vuln pkgs from conda / pip
devcontainers/images pull request #1079
Opened 2024-05-27 16:49 UTC by gauravsaini04

**Dev container name**:
 
 * Anaconda
 
 **Description**:

This PR adds the following functionality : 

* Auto install packages from conda channel / pip pkg managers

2024-05-28 22:17 UTC, samruddhikhandale requested changes

2024-05-28 22:17 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +vulnerable_packages=( "pydantic=2.5.3" "joblib=1.3.1" "mistune=3.0.1" "werkzeug=3.0.3" "transformers=4.36.0" "pillow=10.3.0" "aiohttp=3.9.4" \
This logic seems way too complex, discussing alternatives offline.

2024-05-30 05:36 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +vulnerable_packages=( "pydantic=2.5.3" "joblib=1.3.1" "mistune=3.0.1" "werkzeug=3.0.3" "transformers=4.36.0" "pillow=10.3.0" "aiohttp=3.9.4" \
have corrected based on comments.

2024-05-30 10:43 UTC, Stam098c reviewed
🙏💓☺️👍😊

2024-05-31 00:14 UTC, samruddhikhandale requested changes

2024-05-31 00:14 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +    if (( ${version1[0]} > ${version2[0]} )); then
Why do we need this comparison? 

In the reference sample 👇 , it takes care of comparing the semvers. It finds the max out of required and current in `GREATER_VERSION` and only installs the patch if installed version is not greater or equal to the required version.

```
CURRENT_VERSION=$(git --version | awk '{print $3}')

    REQUIRED_GIT_VERSION="2.45.1"
    GREATER_VERSION=$((echo ${CURRENT_VERSION}; echo ${REQUIRED_GIT_VERSION}) | sort -V | tail -1)

    # Check if the git verson installed is greater or equal to the required git version
    if [ "${CURRENT_VERSION}" != "${GREATER_VERSION}" ]; then
        echo "Git version ${CURRENT_VERSION} installed by the Ubuntu base image is not greater or equal to ${REQUIRED_GIT_VERSION}"
        echo "Installing git from source for ${REQUIRED_GIT_VERSION}..."
        .....
    fi
```

2024-06-03 17:59 UTC, samruddhikhandale requested changes

2024-06-03 17:59 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +        echo "No version for ${packages_array[$i,0]} found in upstream i.e. base image."
As we are patching the existing upstream image, ideally this should never happen.

In future, if our tests start failing then it's an indication for us to clean up this patch. Hence, can we remove it?

2024-06-03 17:59 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +            echo -e "Conda Version: ${CONDA_VERSION} is greater than or equal to the required version: ${REQUIRED_VERSION}. \n";
```suggestion
            echo -e "Found version ${CONDA_VERSION} in the conda channel which is greater than or equal to the required version: ${REQUIRED_VERSION}. \n";
```

2024-06-03 17:59 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +            echo -e "Required version: ${REQUIRED_VERSION} is greater than the conda version: ${CONDA_VERSION}. \n";
```suggestion
            echo -e "Required version ${REQUIRED_VERSION} is greater than the version found in the conda channel  ${CONDA_VERSION}. \n";
```

2024-06-03 17:59 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +    fi
The script you provided is already quite optimized. However, there are a few minor improvements that can be made:

1. Use `pip show --no-index --disable-pip-version-check` to speed up the pip command.
2. Use `conda search --override-channels -c "$channel_name"` to speed up the conda command.
3. Use `python3 -m pip install --upgrade --no-cache-dir` to speed up the pip install command.

Can we make these changes?

2024-06-05 13:47 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +    fi
done

2024-06-05 13:48 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +            echo -e "Required version: ${REQUIRED_VERSION} is greater than the conda version: ${CONDA_VERSION}. \n";
done

2024-06-05 13:48 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +            echo -e "Conda Version: ${CONDA_VERSION} is greater than or equal to the required version: ${REQUIRED_VERSION}. \n";
done

2024-06-05 13:48 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/install_vulnerable_packages.sh
> +        echo "No version for ${packages_array[$i,0]} found in upstream i.e. base image."
done

2024-06-06 20:04 UTC, samruddhikhandale requested changes

2024-06-07 18:26 UTC, Stam098c commented
@gauravsaini04 @samruddhikhandale @Stam098c @eljog

2024-06-11 17:32 UTC, merged