[Universal] - unpin patch versions for dotnet runtime & core
devcontainers/images pull request #1091
Opened 2024-06-12 12:14 UTC by gauravsaini04

**Dev container name**:
 
 * Universal
 
 **Description**:

This PR does the following: 

* Unpin the patch versions for dotnet runtime and core

2024-06-12 17:42 UTC, samruddhikhandale requested changes

2024-06-12 17:42 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> -			// Temporarily pinning as the dotnet-install script is flakey (attempts to install bits of 7.0.19 of Runtime, but 7.0.18 of Core & Runtime)
Can we revert the changes by referring to https://github.com/devcontainers/images/pull/1065/files#diff-0a764bd0944b79c46597d08357a72f308324874b8e25e7d46f302ecc0bc47bafL14-L15 ?

We still want to add .NET 7.0, but we don't want to pin the patch version

2024-06-13 04:22 UTC, gauravsaini04 commented on src/universal/.devcontainer/devcontainer.json
> -			// Temporarily pinning as the dotnet-install script is flakey (attempts to install bits of 7.0.19 of Runtime, but 7.0.18 of Core & Runtime)
ok

2024-06-13 17:11 UTC, samruddhikhandale commented
Looks like the tests are failing, @gauravsaini04 can you take a look?

2024-06-28 21:16 UTC, samruddhikhandale approved these changes

2024-06-28 21:16 UTC, merged