dotnet: improve dev-certs instructions
devcontainers/images pull request #1095
Opened 2024-06-17 16:31 UTC by sliekens

I updated the README for dotnet with a better way to manage HTTPS development certificates for ASP.NET Core.

Previously, it recommended a solution that did not work well in team or open source environments, as it required manual steps, and the solution carried a risk of unintended password disclosure.

I added a solution which does not require manual steps, nor does it have any risk of leaking passwords.

I did not remove the old instructions, but I did add a warning to avoid using it for shared projects.

2024-06-18 23:39 UTC, samruddhikhandale requested changes

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +You can use `dotnet dev-certs https` inside the Dev Container to create a development HTTPS certificate for ASP.NET Core. However, each time the container is recreated, the development certificate wi
```suggestion
You can use `dotnet dev-certs https` inside the dev container to create a development HTTPS certificate for ASP.NET Core. However, each time the container is recreated, the development certificate will be lost. To make the development certificate survive container rebuilds, you can use a named volume. 
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +For example, in `devcontainer.json`, add a named volume for the `x509stores` directory inside the `vscode` user's home folder. Also add a lifecycle script, which adds the development certificate to t
```suggestion
For example, in `devcontainer.json`, add a named volume for the `x509stores` directory inside the `vscode` user's home folder. Also add a lifecycle script, which adds the development certificate to the dev container's trust store.
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +"onCreateCommand": "bash .devcontainer/on-create.sh"
Can we rename the file to `setup-dotnet-certificates.sh` ?

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +You should see the following output when the Dev Container is created:
```suggestion
You should see the following output when the dev container is created:
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +Now this certificate will survive container rebuilds. The certificate will also be trusted by code running inside the container like `System.Net.HttpClient`, or tools like wget and curl. If needed, y
```suggestion
Now this certificate will survive container rebuilds. The certificate will also be trusted by code running inside the container like `System.Net.HttpClient`, or tools like `wget` and `curl`. If needed, you can use Docker Desktop to export the development certificate to a local directory, in case you need to add it to any other trust stores.
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +#### Alternate solution
```suggestion
### Enabling HTTPS in ASP.NET using your own dev certificate
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +You can mount an exported copy of your local dev certificate. This solution is only suitable for private projects, as the password will become part of your `devcontainer.json`. Do not apply this solu
```suggestion
You can mount an exported copy of your local dev certificate for enhanced convenience. This solution is ideal for private projects, but please note that the password will be included in your `devcontainer.json`. Avoid using this method for team projects or open source projects to maintain security best practices.
```

2024-06-18 23:39 UTC, samruddhikhandale commented on src/dotnet/README.md
> +### Enabling HTTPS in ASP.NET Core
```suggestion
### Enabling HTTPS in ASP.NET Core by creating a dev certificate
```

2024-06-19 05:50 UTC, chrmarti approved these changes
Looks good, left one comment.

2024-06-19 05:50 UTC, chrmarti commented on src/dotnet/README.md
> +sudo -E dotnet dev-certs https --export-path /usr/local/share/ca-certificates/https.crt --format pem
Would it make sense to name the file more specifically, e.g., `dotnet-asp.crt`?

2024-06-19 07:34 UTC, sliekens commented on src/dotnet/README.md
> +sudo -E dotnet dev-certs https --export-path /usr/local/share/ca-certificates/https.crt --format pem
Yes, it should be a unique name that doesn't already exist in the `ca-certificates/` dir, how about `dotnet-dev-cert.crt`?

2024-06-19 08:01 UTC, chrmarti commented on src/dotnet/README.md
> +sudo -E dotnet dev-certs https --export-path /usr/local/share/ca-certificates/https.crt --format pem
Sounds good!

2024-06-19 09:07 UTC, sliekens commented on src/dotnet/README.md
> +sudo -E dotnet dev-certs https --export-path /usr/local/share/ca-certificates/https.crt --format pem
Done

2024-06-19 09:17 UTC, sliekens commented on src/dotnet/README.md
> +"onCreateCommand": "bash .devcontainer/on-create.sh"
Renamed to `setup-dotnet-dev-cert.sh` (to match the name of the `dotnet-dev-cert.crt` file)

2024-06-19 09:22 UTC, sliekens commented
Thanks for the reviews @samruddhikhandale @chrmarti 

I applied the suggestions. Can you review again?

2024-06-19 19:06 UTC, samruddhikhandale approved these changes
Appreciate the doc update, thanks!

2024-06-19 19:06 UTC, merged