[universal] - check toolings - monthly task
devcontainers/images pull request #1108
Opened 2024-06-28 08:25 UTC by gauravsaini04

**Dev container name**:
 
 * Universal
 
 **Description**:
 
 This PR updates the toolings versions for `Universal` dev container image to `long term supported` versions if available for the runtime, else uses the `latest` versions of those runtimes
 
 _Changelog_:
 
 * Updated `devcontainer.json` file
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-06-29 11:13 UTC, khgi6565 commented
> **Dev container name**:
> 
> * Universal
> 
> **Description**:
> 
> This PR updates the toolings versions for `Universal` dev container image to `long term supported` versions if available for the runtime, else uses the `latest` versions of those runtimes
> 
> _Changelog_:
> 
> * Updated `devcontainer.json` file
> 
> **Checklist**:
> 
> * [x]    Checked that applied changes work as expected

2024-07-03 23:13 UTC, samruddhikhandale requested changes

2024-07-03 23:13 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +            "version": "3.12.3",
Oryx has compatibility issues with the version of Python installed, hence can we update the version based on the closest lts version which is supported by oryx?

Looking at https://github.com/devcontainers/images/actions/runs/9771395221/job/26974077297?pr=1108#step:3:38957 we'd need `3.12.1`

![image](https://github.com/user-attachments/assets/dda8bb02-7667-43e7-b755-c2cc58b40e83)

2024-07-03 23:13 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +            "version": "3.12.3",
That's the reason why we have tests to ensure the installed version is compatible with Oryx

2024-07-03 23:13 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/patch-python/install.sh
> -# https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897
Niceeee

2024-07-08 01:12 UTC, gauravsaini04 commented on src/universal/.devcontainer/devcontainer.json
> +            "version": "3.12.3",
thanks for info, done

2024-07-12 20:02 UTC, samruddhikhandale requested changes

2024-07-12 20:02 UTC, samruddhikhandale commented on src/universal/.devcontainer/devcontainer.json
> +            "version": "3.3.3",
```suggestion
            "version": "3.3.4",
```

Can we update to 3.3.4?  Hoping to not run into a similar issue as https://github.com/devcontainers/images/issues/1123

2024-07-16 20:36 UTC, samruddhikhandale approved these changes

2024-07-16 20:36 UTC, merged