[cpp] - buster - EOL
devcontainers/images pull request #1127
Opened 2024-07-12 07:01 UTC by gauravsaini04

**Devcontainer name**

* CPP

**Changes**

* Changes to manifest.json for CPP dev container image's files for buster EOL

2024-07-12 20:06 UTC, samruddhikhandale requested changes

2024-07-12 20:06 UTC, samruddhikhandale commented on src/cpp/manifest.json
>  		"bookworm",
Can we cleanup from README file as well?

2024-07-12 20:06 UTC, samruddhikhandale commented on src/cpp/manifest.json
>  		"bookworm",
Can we cleanup https://github.com/devcontainers/images/blob/fea177cf129ebfe01c7b50263fc1a475f0bd3ea3/src/cpp/.devcontainer/base-scripts/install-vcpkg.sh#L14relevant code ?

2024-07-14 02:00 UTC, gauravsaini04 commented on src/cpp/manifest.json
>  		"bookworm",
done

2024-07-14 02:01 UTC, gauravsaini04 commented on src/cpp/manifest.json
>  		"bookworm",
done

2024-07-16 20:37 UTC, samruddhikhandale approved these changes

2024-07-16 20:37 UTC, merged