[base-ubuntu] - remove existing ubuntu user
devcontainers/images pull request #1170
Opened 2024-08-23 06:12 UTC by gauravsaini04

**Devcontainer Names**

* base-ubuntu

**Description**

* This PR attemtps to make the following changes:
	- Removes the existing `ubuntu` user provided by the base-image for `ubuntu-noble` base image i.e. existing user blocking uid & gid 1000
	
**_Changelog_** 

* Changed the `Dockerfile` and wrote a test case for the devcontainer image

**Checklist**

* [x] Checked that applied changes work as expected

2024-08-23 23:29 UTC, samruddhikhandale requested changes

2024-08-23 23:29 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +    else \
The `vscode` user is created by `common-utils` Feature. Hence, you don't need to create it in the dockerfile. 

I was referring to re-adding https://github.com/devcontainers/images/pull/1036/files#diff-eaa1990d44094d26a8143b63dc994e880f6b4fa69140f3b6bf270c4acecbf22aL10-L11

2024-08-23 23:29 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
Along with deleting the user, can you also remove user's home directory and delete the group associated with the user? 

This should free up the 1000 uid and gid

2024-08-23 23:29 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        else \
This is fine for debugging, but when you open a final PR, let's remove this.
Let our tests validate this.

2024-08-24 02:27 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +    else \
added back again 👍

2024-08-24 02:28 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
userdel command supposed to delete the user's home dir as well, have added command to delete user's group

2024-08-24 02:28 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        else \
ok

2024-08-24 02:34 UTC, gauravsaini04 commented
```
https://github.com/devcontainers/images/actions/runs/10534973968/job/29193352531?pr=1170#step:3:2854
```
The failing tests would pass in the dev codespace env.

2024-08-27 23:12 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +    fi > /tmp/logfile.txt 2>&1
```suggestion
    fi
```

2024-08-27 23:12 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +    fi > /tmp/logfile.txt 2>&1
It's good for debugging, but let's not have it in the image

2024-08-27 23:12 UTC, samruddhikhandale commented on src/dotnet/.devcontainer/Dockerfile
> +ARG VARIANT=8.0-noble
Revert this change and add a test to validate noble.

2024-08-27 23:12 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
For debugging only: Can you verify that the UID and GID are no longer in use with `getent passwd 1000 && getent group 1000` ?

2024-08-27 23:12 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
Can you check by removing entries from `/etc/passwd` and `/etc/group`

2024-08-28 15:53 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
yes, they are no longer in use when checked with getent

2024-08-28 15:54 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
no entries were found for 1000 uid and gid in the files after removal

2024-09-09 23:58 UTC, samruddhikhandale requested changes

2024-09-10 03:57 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
No actually `userdel` command already deleted everything related to `Ubuntu` user occupying `1000` uid and gid so it's just a failed check after trying to delete `ubuntu` group later.

2024-09-10 04:04 UTC, gauravsaini04 commented on src/base-ubuntu/test-project/test.sh
> +check "uid" bash -c "id -u vscode | grep 1001"
ok

2024-09-10 04:04 UTC, gauravsaini04 commented on src/base-ubuntu/test-project/test.sh
> +check "uid" bash -c "id -u vscode | grep 1001"
sure

2024-09-11 00:56 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
If that's the case, then should we remove https://github.com/devcontainers/images/pull/1170/files#diff-8bc3ab047cce2f0dc035c0856710e0988c4a9bb82687cfa3d182866665ebad42R14

2024-09-11 00:56 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
@gauravsaini04 Let's only keep the commands which are actually needed for deleting `ubuntu` user and clearing up 1000 uids/gids

2024-09-11 05:52 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
sure thanks for the inputs..

2024-09-16 20:38 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
> @gauravsaini04 Let's only keep the commands which are actually needed for deleting ubuntu user and clearing up 1000 uids/gids

@gauravsaini04 I don't think the code changed post my last review. Am I missing anything?

2024-09-16 23:55 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
made more changes

2024-09-18 22:15 UTC, samruddhikhandale requested changes

2024-09-18 22:15 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +ENV VARIANT=${VARIANT}
```suggestion
ARG VARIANT
```

Do we need `VARIANT` at runtime? I wonder if having it at build time should be sufficient in this case?

2024-09-18 22:15 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "✔️ User ubuntu does not exist"; \
```suggestion
            echo "User 'ubuntu' does not exist for $VARIANT"; \
```

2024-09-18 22:15 UTC, samruddhikhandale commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "❕Failed to delete ubuntu user"; \
```suggestion
            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \
```

2024-09-19 00:29 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +ENV VARIANT=${VARIANT}
yes that's right, works without env variable declaration as well..

2024-09-19 00:29 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "✔️ User ubuntu does not exist"; \
done

2024-09-19 00:30 UTC, gauravsaini04 commented on src/base-ubuntu/.devcontainer/Dockerfile
> +            echo "Deleting user ubuntu" && userdel -f -r ubuntu || echo "❕Failed to delete ubuntu user"; \
done

2024-09-19 22:51 UTC, samruddhikhandale approved these changes

2024-09-19 22:51 UTC, merged