[dotnet] - 7.0 & 6.0 EOL for noble
devcontainers/images pull request #1171
Opened 2024-08-23 10:17 UTC by gauravsaini04

**Devcontainer Image**

* Dotnet

**Description**

* EOL changes for `7.0` & `6.0` for `noble-numbat` variant

**_Changelog_**

* changes to `manifest.json` made

**Checlist**

* [x] Checked that applied changes work as expected

2024-08-23 23:31 UTC, samruddhikhandale requested changes

2024-08-23 23:31 UTC, samruddhikhandale commented on src/dotnet/manifest.json
> +	"version": "1.3.0",
Let's revert this, for images release we create an isolated PR for version bumps.

2024-08-23 23:31 UTC, samruddhikhandale commented on src/dotnet/manifest.json
>  		"7.0-bookworm-slim",
Shouldn't we also remove all variants for .NET 7 as it's EOL?

2024-08-27 01:30 UTC, goxijana3 commented on src/dotnet/manifest.json
>  		"7.0-bookworm-slim",
I  wiil kill all

2024-08-27 23:00 UTC, samruddhikhandale requested changes

2024-08-27 23:00 UTC, samruddhikhandale commented on src/dotnet/manifest.json
>  		"8.0-noble",
Can you update Readme file as well?

2024-08-28 03:27 UTC, gauravsaini04 commented on src/dotnet/manifest.json
>  		"8.0-noble",
yeah done !

2024-08-28 03:28 UTC, gauravsaini04 commented on src/dotnet/manifest.json
>  		"7.0-bookworm-slim",
yeah done !

2024-08-28 03:28 UTC, gauravsaini04 commented on src/dotnet/manifest.json
> +	"version": "1.3.0",
done

2024-08-28 16:56 UTC, samruddhikhandale approved these changes

2024-08-28 16:56 UTC, merged