[dotnet] - remove ubuntu:noble's ubuntu user capturing 1000 uid & gid
devcontainers/images pull request #1178
Opened 2024-08-30 08:01 UTC by gauravsaini04

**Devcontainer Names**

* dotnet

**Description**

* This PR attemtps to make the following changes:
	- Removes the existing `ubuntu` user provided by the base-image for `ubuntu-noble` base image i.e. existing user blocking uid & gid 1000
	
**_Changelog_** 

* Changed the `Dockerfile` and wrote a test case for the devcontainer image if ubuntu:noble is used as base image o.s

**Checklist**

* [x] Checked that applied changes work as expected

2024-09-24 19:29 UTC, samruddhikhandale requested changes

2024-09-24 19:29 UTC, samruddhikhandale commented on src/dotnet/test-project/test.sh
> +check_ubuntu_user() {
Thanks for adding these, however, let's remove these tests as we would never update the default image to be `noble`

2024-09-24 19:29 UTC, samruddhikhandale commented on src/dotnet/.devcontainer/Dockerfile
> +        if id "ubuntu" &>/dev/null; then \
Testing these changes and pushing to dev tags
https://github.com/devcontainers/images/actions/runs/11020617403

2024-09-25 22:02 UTC, samruddhikhandale commented on src/dotnet/.devcontainer/Dockerfile
> +RUN if [ "${VARIANT#*noble}" != "$VARIANT"  ]; then \
Can you add back these changes which pins to 1000? 

https://github.com/devcontainers/images/pull/1195/files#diff-cc0cf9f2ed094e192be020fc2105581e6a56adde975fe41251b6c7debc8f6cf4L10-L12

2024-09-26 07:15 UTC, gauravsaini04 commented on src/dotnet/.devcontainer/Dockerfile
> +RUN if [ "${VARIANT#*noble}" != "$VARIANT"  ]; then \
sure

2024-09-26 07:17 UTC, gauravsaini04 commented on src/dotnet/test-project/test.sh
> +check_ubuntu_user() {
ok

2024-09-26 19:53 UTC, samruddhikhandale approved these changes

2024-09-26 19:53 UTC, merged