[python] - setuptools - GHSA-cx63-2mw6-8hw5 - v69.0.3 to v70.0.0
devcontainers/images pull request #1219
Opened 2024-10-24 13:01 UTC by gauravsaini04

**Devcontainer Name**
* Python

**Description**
* PR been raised for remediating a security vulnerability [ GHSA-cx63-2mw6-8hw5 ], needed to update setuptools to v70.0.0

**_changelog_**
* Changes to Dockerfile
* Changes to test file

**Checklist**
- [x] Checked that applied changes work as expected

2024-11-22 22:54 UTC, eljog commented on src/python/.devcontainer/Dockerfile
> +    setuptools==70.0.0 \
I understand this is sufficient for fixing the vulnerability.. 
What is the latest version available for this package? And why don't we go to the latest version instead?

2024-11-28 15:23 UTC, Kaniska244 commented on src/python/.devcontainer/Dockerfile
> +    setuptools==70.0.0 \
Hi @eljog ,

I have updated the python setuptools versions to the latest version 75.6.0. Kindly let me know in case of further concerns on this.

2024-12-12 21:48 UTC, ddoyle2017 approved these changes
Looks good 👍

2024-12-12 21:51 UTC, ddoyle2017 requested changes
Need to re-review

2024-12-12 21:52 UTC, ddoyle2017 approved these changes
Looks fine!

2024-12-12 21:52 UTC, merged