Support Ruby 3.4
devcontainers/images pull request #1276
Opened 2024-12-31 10:23 UTC by Kaniska244

**Ref**: #90 

**Devcontainer name**

Ruby

**Description**

This pr adds 834 latest ruby version to the supported versions list in ruby image.

**Changelog**

- Changes are there in manifest.json and readme.md file for ruby image to add support to latest 3.4 ruby version.

**Checklist**

- Checked that applied changed work as expected

2025-01-06 15:35 UTC, NelcifranSofto commented
wow Finally !!!!

2025-01-09 00:31 UTC, ddoyle2017 requested changes
Changes look good! However, the [Dockerfile](https://github.com/devcontainers/images/blob/8ab31b257574d3ef183293ccf15010f6e6e7db57/src/ruby/.devcontainer/Dockerfile#L1) also needs to be updated with a reference to 3.4

2025-01-09 15:12 UTC, ddoyle2017 requested changes
Thanks for updating the `Dockerfile`! There's a small error that needs to be fixed and I think we're good to go

2025-01-09 15:12 UTC, ddoyle2017 commented on src/ruby/README.md
> +- `mcr.microsoft.com/devcontainers/ruby:3.3` (or `3.4-bookworm`, `3.4-bullseye` to pin to an OS version)
I think there's a typo here. `mcr.microsoft.com/devcontainers/ruby:3.3` should be `mcr.microsoft.com/devcontainers/ruby:3.4`

2025-01-09 16:01 UTC, Kaniska244 commented on src/ruby/README.md
> +- `mcr.microsoft.com/devcontainers/ruby:3.3` (or `3.4-bookworm`, `3.4-bullseye` to pin to an OS version)
Hi @ddoyle2017 ,

Thanks a lot for pointing that one out. I have corrected the same. Would you kindly review once again.

With Regards,
Kaniska

2025-01-09 21:17 UTC, merged

2025-01-21 07:41 UTC, cgrothaus commented
The docker image for 3.4 is not yet published (https://mcr.microsoft.com/en-us/artifact/mar/devcontainers/ruby/tags only has `dev-3.4`). When will this happen?
(Sorry if I am asking questions that would better be asked somewhere else – I don't know how this is all connected).

2025-02-28 05:19 UTC, ashkulz commented
@Kaniska244 I can see `dev-3.4` tag being published but not `3.4` -- do you know when it'll get published?