[universal] Conda: patch Python due to CVE-2023-32681 and GHSA-5cpq-8wj7-hf2v
devcontainers/images pull request #627
Opened 2023-06-15 13:39 UTC by alexander-smolyakov

**Dev container name**: 

- universal

**Issue description**:

This PR aims to address CVE-2023-32681 and GHSA-5cpq-8wj7-hf2v security vulnerabilities. These vulnerabilities come from Python distribution which ships with Conda.

**Fix description**:

In the `universal` devcontainer, we have three instances of Python distribution:

```mermaid
flowchart TD
    CF[conda feature] --> CFP[Python 3.10.4]
    PF[python feature] --> PFP1[Python 3.10.8]
    PF --> PFP2[Python 3.9.16]
    CFP --"/opt/conda/bin/python3"--> U[universal devconatiner]
    PFP1 --"/usr/local/python/3.10.8/bin/python (set to current)"--> U[universal devconatiner]
    PFP2 --"/usr/local/python/3.9.16/bin/python"--> U[universal devconatiner]
```

Originally fixes were applied during the `setup-user` feature installation and the feature installation queue looks the following:

```mermaid
flowchart TD
   D[Dockerfile] --"..."--> PF[python feature]
   PF --> PPF[patch-python feature] 
   PPF --> MLF[machine-learning-packages feature]
   MLF --"..." --> CF[conda feature]
   CF --"..." --> SU[setup-user feature]
```

This approach resulted in the Anaconda Python distribution containing vulnerable packages in `site-packages` folders, and this triggered our security checks. Additionally, when running the `conda list` command, it's listed vulnerable packages. 

The `pip` doesn't provide the ability to remove packages from the specific `site-packages` folder. When we try to remove any packages for related Python distribution during `setup-user` installation, we face the following situation:

```console
codespace ➜ / $ /opt/conda/bin/python3 -m pip uninstall requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
  Would remove:
    /home/codespace/.local/lib/python3.10/site-packages/requests-2.31.0.dist-info/*
    /home/codespace/.local/lib/python3.10/site-packages/requests/*
Proceed (Y/n)?
```

The `pip` trying to remove the package from the `/home/codespace/.local/lib/python3.10/site-packages/` folder when we need to remove the package from `opt/conda/lib/python3.10/site-packages`. In order to remove package `opt/conda/lib/python3.10/site-packages`, we should run the `/opt/conda/bin/python3 -m pip uninstall requests` command twice because we installed additional Python distribution via the `python` feature:

```console
codespace ➜ / $ /opt/conda/bin/python3 -m pip uninstall requests
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
  Would remove:
    /home/codespace/.local/lib/python3.10/site-packages/requests-2.31.0.dist-info/*
    /home/codespace/.local/lib/python3.10/site-packages/requests/*
Proceed (Y/n)? y
  Successfully uninstalled requests-2.31.0
codespace ➜ / $ /opt/conda/bin/python3 -m pip uninstall requests
Found existing installation: requests 2.28.1
Uninstalling requests-2.28.1:
  Would remove:
    /opt/conda/lib/python3.10/site-packages/requests-2.28.1.dist-info/*
    /opt/conda/lib/python3.10/site-packages/requests/*
Proceed (Y/n)? y
  Successfully uninstalled requests-2.28.1
codespace ➜ / $ /opt/conda/bin/python3 -m pip uninstall requests
WARNING: Skipping requests as it is not installed.
```

The other side effect of this approach is that it affects Python distribution coming from the `python` feature:

```console
codespace ➜ / $ which python
/home/codespace/.python/current/bin/python
codespace ➜ / $ python --version
Python 3.10.8
codespace ➜ / $ python -c "import requests; print(requests.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

To avoid such a situation, we have to reorganize the features installation queue to install the `conda` feature and apply all patches to it before the `python` feature installation.

**Changelog**:

- Reorganized features installation queue;
- Implemented patches to bump up versions for the following packages:  
  - `cryptography`, `pyopenssl` to address GHSA-5cpq-8wj7-hf2v;
  - requests to address GHSA-j8r2-6x86-q33q;
- Introduced patch-conda feature.

**Checklist**:

- [ ] Checked that applied changes work as expected

2023-06-15 17:03 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/patch-conda/install.sh
> +update_package /opt/conda/bin/python3 pyopenssl
Can we add tests to validate these `update_package` changes?

2023-06-16 08:01 UTC, alexander-smolyakov commented on src/universal/.devcontainer/devcontainer.json
> +        "./local-features/patch-python": "latest",
Fixed in 97ed40c0ede9ef4ef999cde23906a0674c9ffd72

2023-06-16 08:01 UTC, alexander-smolyakov commented on src/universal/.devcontainer/local-features/patch-conda/devcontainer-feature.json
> +}
> Can we remove the install property?

Removed in 97ed40c0ede9ef4ef999cde23906a0674c9ffd72

2023-06-16 08:02 UTC, alexander-smolyakov commented on src/universal/.devcontainer/local-features/patch-conda/install.sh
> +update_package /opt/conda/bin/python3 pyopenssl
Added tests in e27d89ffa6cefc89fff278d50225238b9c635bec

2023-06-20 17:33 UTC, samruddhikhandale requested changes
Left one comment, can you also help resolve the merge conflicts? thanks!

2023-06-20 17:33 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/patch-conda/devcontainer-feature.json
> +    "name": "Patch Conda Packages",
Would this also need an `installsAfter` property? which would ensure it runs after the `conda `Feature?

2023-06-21 16:06 UTC, alexander-smolyakov commented on src/universal/.devcontainer/local-features/patch-conda/devcontainer-feature.json
> +    "name": "Patch Conda Packages",
Good point! Fixed in f172ea6bdaf89aa92d83c4c380de2e61559423a8.
Also, I locked packages versions in https://github.com/devcontainers/images/pull/627/commits/c553c4e55822f91becab5285a52d341558326362 as we discussed here - https://github.com/devcontainers/images/pull/634#discussion_r1235997437

2023-06-21 16:15 UTC, samruddhikhandale commented on src/universal/.devcontainer/local-features/patch-conda/install.sh
> +update_package /opt/conda/bin/python3 requests "2.31.0"
Do we have a similar issue as discussed in https://github.com/devcontainers/images/pull/634#discussion_r1235422928 ?

Should we add these checks and validate? 👇 

https://github.com/devcontainers/images/pull/634/files#diff-8ba43d40bb42e487114045bafc2cc4b0e0d149405531e15341f420e1dbc420a6R32-R34

2023-06-21 16:20 UTC, alexander-smolyakov commented on src/universal/.devcontainer/local-features/patch-conda/install.sh
> +update_package /opt/conda/bin/python3 requests "2.31.0"
As I can see, we don't have such tests for the universal container. I will add them and check if the same issue occurs.

2023-08-02 16:01 UTC, samruddhikhandale approved these changes

2023-08-02 16:01 UTC, merged