[anaconda] Refactor `Dockerfile` to decrease image size
devcontainers/images pull request #692
Opened 2023-08-02 15:38 UTC by alexander-smolyakov

**Description**:

During patch development, the CI checks for the `anaconda` devcontainer started to fail due to the space limit on a hosted agent. 

After investigation, it turned out that layer where we set up ownership and permission for the `opt` folder consumes a lot of space. This is related to using of `chown` and `chmod` commands.

_Related code_:

https://github.com/devcontainers/images/blob/47bbd234b8ecd36cd43c5bb9b36d986f19cc929c/src/anaconda/.devcontainer/Dockerfile#L88-L92

**Fix**:

To fix this and reduce image size, the Docker file was refactored:

- The `pip install` and `conda install` commands now executes against the `continuumio/anaconda3` image. This will allow us to not worry about `opt` folder permissions and ownership since we can set them up during `COPY` instruction;

- The `COPY` instruction [now sets up permissions](https://docs.docker.com/engine/reference/builder/#copy) and ownership for the `opt` folder. The `COPY` instruction will not create an additional layer, which should help decrease image size;

- Previous commands for setting up permissions and ownership were removed.

2023-08-02 22:47 UTC, samruddhikhandale requested changes
It is super cool to see the image size decrease from ~9 GB to ~5 GB 🎉 ✨ 
Thank you! 

Left some comments!

2023-08-02 22:47 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
>  FROM mcr.microsoft.com/devcontainers/base:0-bullseye
Looks like we missed bumping the major version, can we update this? Thanks! 

```suggestion
FROM mcr.microsoft.com/devcontainers/base:1-bullseye
```

2023-08-02 22:47 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=070 --from=upstream /opt /opt/
Comparing this image changes with the prod image, we are missing some permissions on `/opt/conda`. Can we sync that? thanks! 

<img width="1277" alt="image" src="https://github.com/devcontainers/images/assets/24955913/622ada0e-ec58-495a-88c4-2e049869fb74">

2023-08-03 09:28 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
>  FROM mcr.microsoft.com/devcontainers/base:0-bullseye
I bumped container version in 6e511af45af5666dbda0bda29502efaab7c86fce

2023-08-03 09:29 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=070 --from=upstream /opt /opt/
I updated permissions in 6e511af45af5666dbda0bda29502efaab7c86fce

2023-08-03 21:48 UTC, samruddhikhandale approved these changes

2023-08-03 21:48 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
```suggestion
COPY --chown=:conda --chmod=775 --from=upstream /opt/conda /opt/conda
```

> && chown -R :conda /opt/conda \
    && chmod -R g+w /opt/conda \
    
Syncing with ^

2023-08-03 21:48 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
I agree that the current upstream image only adds `conda` folder to `/opt/`, however, that could change anytime. Hence, it would be nice to be as precise as possible!

2023-08-04 08:57 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
Good point! I applied the suggested changes.

2023-08-04 12:21 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
Related changes caused the permission denied error. I'm investigating why this happened.
Error: https://github.com/devcontainers/images/actions/runs/5760266653/job/15615884009#step:3:5724

2023-08-08 14:25 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
The issue is related to the fact that when using chown and chmod functions with the `COPY` command, Docker updates the metadata of folder content but not the folder itself. I updated Dockerfile to set permissions to the `opt/conda` folder: https://github.com/devcontainers/images/pull/692/commits/ffece92eedb493a66f2cd3798efecbfa29c7a734.

Results:

> COPY /opt/conda /opt/conda # buildkit

```console
Permission     UID:GID       Size  Filetree
drwxr-xr-x         0:0     4.2 GB  └── opt 
drwxr-xr-x       0:900     4.2 GB      └── conda
```

> COPY /opt/ /opt/ # buildkit

```console
Permission     UID:GID       Size  Filetree
drwxr-xr-x         0:0     4.2 GB  └── opt
drwxrwxr-x       0:900     4.2 GB      └── conda
```

> COPY /opt/conda /opt/conda # buildkit
> RUN |1 USERNAME=vscode /bin/sh -c chmod =2775 /opt/conda # buildkit

```console
Permission     UID:GID       Size  Filetree
drwxr-xr-x         0:0        0 B  └── opt
drwxrwsr-x       0:900        0 B      └── conda
```

2023-08-08 18:31 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +COPY --chown=:conda --chmod=775 --from=upstream /opt /opt/
Nice, thanks!

2023-08-08 18:31 UTC, merged