[Anaconda] Update cryptography package due to [GHSA-jfhm-5ghh-2f97](https://github.com/advisories/GHSA-jfhm-5ghh-2f97)
devcontainers/images pull request #901
Opened 2023-12-26 02:39 UTC by gauravsaini04

**Dev container name**: 
* Anaconda

**Description**: 

This PR patches the following vulnerabilities:

* [GHSA-jfhm-5ghh-2f97](https://github.com/advisories/GHSA-jfhm-5ghh-2f97) - related to the `cryptography` package;

These vulnerabilities come from the continuumio/anaconda3 image used upstream for the anaconda devcontainer.

*Changelog*:

* Updated Dockerfile
  * Locked version for patched Python package;
    * `cryptography` - _minimum package version set to `41.0.6`_; 
  
* Updated tests to verify `cryptography` minimum version (Minimum package version set to `41.0.6` which fixes [GHSA-jfhm-5ghh-2f97](https://github.com/advisories/GHSA-jfhm-5ghh-2f97));

**Checklist**:

* [x]  Checked that applied changes work as expected

2023-12-27 09:24 UTC, alexander-smolyakov requested changes

2023-12-27 09:24 UTC, alexander-smolyakov commented on src/anaconda/test-project/test.sh
> -checkPythonPackageVersion "transformers" "4.30.0"
It looks like an unrelated change, please revert it.

2023-12-27 09:24 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +    urllib3==1.26.18
Nit: extra whitespace

2023-12-27 09:24 UTC, alexander-smolyakov commented on src/anaconda/.devcontainer/Dockerfile
> +    cryptography==41.0.6
As I can see, the Anaconda default channel contains `cryptography` v41.0.7: https://anaconda.org/anaconda/cryptography/files

Could you rework the patch to install the package from the conda channel? For compatibility sake.

2023-12-27 14:55 UTC, gauravsaini04 commented on src/anaconda/test-project/test.sh
> -checkPythonPackageVersion "transformers" "4.30.0"
Have corrected it. Thanks Alex.

2023-12-27 14:56 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/Dockerfile
> +    urllib3==1.26.18
Have corrected it

2023-12-27 14:56 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/Dockerfile
> +    cryptography==41.0.6
Corrected it.

2023-12-27 14:57 UTC, alexander-smolyakov approved these changes

2024-01-03 21:15 UTC, eljog approved these changes

2024-01-04 03:27 UTC, gauravsaini04 commented
Hi @eljog, have resolved merge conflicts

2024-01-04 17:22 UTC, eljog approved these changes

2024-01-04 17:23 UTC, merged