[Anaconda] - Jupyterlab - Patch security vulnerability GHSA-44cc-43rp-5947
devcontainers/images pull request #939
Opened 2024-01-29 15:32 UTC by gauravsaini04

**Dev container name**:
 
 * anaconda
 
 **Description**:
 
 This PR patches the following vulnerability:
 
 * [GHSA-44cc-43rp-5947](https://github.com/advisories/GHSA-44cc-43rp-5947) - related to the `jupyterlab` package;
 
 This vulnerability comes from the continuumio/anaconda3 image used upstream for the anaconda devcontainer.
 
 _Changelog_:
 
 * Updated Dockerfile
   
   * Locked version for patched conda package;
    
     * `jupyterlab` - _minimum package version set to `4.0.8`_;
 * Updated tests to verify `jupyterlab` minimum version (Minimum package version set to `4.0.8` which fixes [GHSA-44cc-43rp-5947](https://github.com/advisories/GHSA-44cc-43rp-5947));
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-01-29 19:15 UTC, samruddhikhandale requested changes
Left some clarifying questions!

2024-01-29 19:15 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +    jupyterlab==4.0.8
What is the current version of `jupyterlab`?

2024-01-29 19:15 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +    jupyterlab==4.0.8
```suggestion
    jupyterlab==4.0.11
```

Should this be `4.0.11` provided the current major version is 4?

![image](https://github.com/devcontainers/images/assets/24955913/b4f32eb9-26e1-4454-b264-7820854bad3c)

2024-01-30 05:09 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/Dockerfile
> +    jupyterlab==4.0.8
Actually, It slipped my mind about the version to be actually updated to, I only gave weightage to latest available in anaconda channel. Have updated now to pull from pip rather than anaconda channel.

2024-01-30 05:10 UTC, gauravsaini04 commented on src/anaconda/.devcontainer/Dockerfile
> +    jupyterlab==4.0.8
Have updated with new commits w.r.t latest version that resolves the vulnerability. Thanks !

2024-01-30 17:58 UTC, samruddhikhandale requested changes
One comment, otherwise LGTM!

2024-01-30 17:58 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +    transformers==4.36.0 \
Hmm.. I see the same issue here as https://github.com/devcontainers/features/pull/815#discussion_r1471696865

I wonder what `git` commands are leading to this, this makes it hard review the changes 😅
Let me know if you need help for fixing.

2024-01-30 17:58 UTC, samruddhikhandale commented on src/anaconda/.devcontainer/Dockerfile
> +    transformers==4.36.0 \
This usually happens when your branch is not up-to-date with the `main` branch, or when you have merged another branch into your branch. Here are a few possible reasons:

1. Your branch is behind the main branch: If the main branch has been updated since you created your branch, and you haven't pulled the latest changes into your branch, then your PR will show those changes as differences.

2. You've merged another branch into your branch: If you've merged another branch into your branch, then all the changes from that branch will appear in your PR.

3. You've accidentally committed someone else's changes: If you've accidentally committed changes that someone else made, then those changes will appear in your PR.

To avoid this, always make sure your branch is up-to-date with the `main` branch before you start making changes. You can do this by pulling the latest changes from the `main` branch into your branch. If you've already made changes and find that your branch is behind, you can rebase your branch onto the `main` branch. This will update your branch with the latest changes from the `main` branch, and move your changes on top of those.

2024-02-01 21:08 UTC, samruddhikhandale approved these changes

2024-02-01 21:08 UTC, merged