[Anaconda] - [aiohttp] -  Address Security Vulnerability - GHSA-5h86-8mv2-jq9f
devcontainers/images pull request #949
Opened 2024-02-07 10:20 UTC by gauravsaini04

**Dev container name**:
 
 * Anaconda
 
 **Description**:
 
 This PR patches the following vulnerability:
 
 * [GHSA-5h86-8mv2-jq9f](https://github.com/advisories/GHSA-5h86-8mv2-jq9f) - related to the `aiohttp` package;
 
 This vulnerability comes from the continuumio/anaconda3 image used upstream for the anaconda devcontainer.
 
 _Changelog_:
 
 * Updated Dockerfile
   * Locked version for patched python package;
     * `aiohttp` - _minimum package version set to `3.9.2`_;
   * Removed locked version for previously patched conda package;
     * `aiohttp` - _minimum package version was set to `3.9.0`_;
 * Updated tests to verify `aiohttp` minimum version (Minimum package version set to `3.9.2` which fixes [GHSA-5h86-8mv2-jq9f](https://github.com/advisories/GHSA-5h86-8mv2-jq9f));
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-02-07 18:26 UTC, samruddhikhandale requested changes

2024-02-07 18:26 UTC, samruddhikhandale commented on src/anaconda/test-project/test.sh
>  checkPythonPackageVersion "transformers" "4.36.0"
We have some failing checks, can you fix them? 

https://github.com/devcontainers/images/actions/runs/7813269949/job/21312054793?pr=949#step:3:4694

Looks like these have started failing on `main` as well. See https://github.com/devcontainers/images/actions/workflows/smoke-anaconda.yaml

2024-02-07 18:26 UTC, samruddhikhandale commented on src/anaconda/test-project/test.sh
>  checkPythonPackageVersion "transformers" "4.36.0"
Can you update to this line https://github.com/devcontainers/images/blob/main/.github/workflows/smoke-anaconda.yaml#L17C1-L17C47 to 👇 

```
runs-on: devcontainer-image-builder-ubuntu
```

This should ideally fix `No space left on device')` error

2024-02-08 00:14 UTC, gauravsaini04 commented on src/anaconda/test-project/test.sh
>  checkPythonPackageVersion "transformers" "4.36.0"
Have done. 👍

2024-02-08 00:37 UTC, samruddhikhandale approved these changes
⚡

2024-02-08 00:37 UTC, merged