[MIniconda] - Cryptography - Patch security vulnerability - GHSA-3ww4-gg4f-jr7f
devcontainers/images pull request #965
Opened 2024-02-14 09:31 UTC by gauravsaini04

**Dev container name**:
 
 * Miniconda
 
 **Description**:
 
 This PR patches the following vulnerability:
 
 * [GHSA-3ww4-gg4f-jr7f](https://github.com/advisories/GHSA-3ww4-gg4f-jr7f) - related to the `cryptography` package;
 
 This vulnerability comes from the coninuumio/miniconda3 image used upstream for the Miniconda devcontainer.
 
 _Changelog_:
 
 * Updated Dockerfile
   * Upgraded version for patched conda package;
     * `cryptography` - _minimum package version is set to `42.0.2`_;
	 
 * Updated tests to verify `cryptography` minimum version (Minimum package version set to `42.0.2` which fixes [GHSA-3ww4-gg4f-jr7f](https://github.com/advisories/GHSA-3ww4-gg4f-jr7f));
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-02-14 17:23 UTC, samruddhikhandale requested changes

2024-02-14 17:23 UTC, samruddhikhandale commented on src/miniconda/.devcontainer/Dockerfile
> +    cryptography==42.0.2
Question: The patched version is `42.0.0`, so why was it updated to `42.0.2`?

2024-02-14 17:24 UTC, samruddhikhandale commented on src/miniconda/test-project/test.sh
There are failing tests, can you take a look? https://github.com/devcontainers/images/actions/runs/7899131830/job/21557930111?pr=965#step:3:2888

2024-02-15 03:32 UTC, gauravsaini04 commented on src/miniconda/.devcontainer/Dockerfile
> +    cryptography==42.0.2
Because it is preferred to get the latest version even if higher than the required version from the anaconda channel and I could only find this version after 41.0.7 in anaconda channel for cryptography and not exactly 42.0.0. ( alex had mentioned like that to me )

2024-02-15 05:58 UTC, gauravsaini04 commented on src/miniconda/test-project/test.sh
Have removed the test for `checkCondaPackageVersion "pyopenssl" "23.2.0"` as no pyopenssl package was found inside the dev container when checked with commands like `pip show pyopenssl` or `conda list | grep -i pyopenssl`

2024-02-15 22:26 UTC, samruddhikhandale requested changes

2024-02-15 22:26 UTC, samruddhikhandale commented on src/miniconda/test-project/test.sh
Installing new version of `crypotography` removed `pyopenssl`, see https://github.com/devcontainers/images/actions/runs/7899131830/job/21557930111#step:3:719

That doesn't sound good and could be a breaking change for users who were previously expecting `pyopenssl`

Can you install a compatible version of `pyopenssl` which works with `crypotography` ? See https://github.com/devcontainers/images/pull/634 for reference

See https://github.com/devcontainers/images/issues/486 for a past problem due to version incompatibility.

2024-02-15 22:26 UTC, samruddhikhandale commented on src/miniconda/.devcontainer/Dockerfile
> +    cryptography==42.0.2
> Because it is preferred to get the latest version

As we are patching, it is not preferred in our case to always install `latest`. We want to get to a point where the upstream image updates it and we can remove this patch. 

> I could only find this version after 41.0.7 in anaconda channel for cryptography and not exactly 42.0.0

This explanation sounds reasonable

2024-02-15 23:33 UTC, gauravsaini04 commented on src/miniconda/test-project/test.sh
Have installed `pyopenssl v24.0.0` as compatible version with `cryptography v42.0.2` (as mentioned in https://pypi.org/project/pyOpenSSL/)

2024-02-15 23:38 UTC, samruddhikhandale requested changes

2024-02-15 23:38 UTC, samruddhikhandale commented on src/miniconda/.devcontainer/Dockerfile
> +    pyopenssl==24.0.0
Curious, why don't we install it with `conda`? Similar to https://github.com/devcontainers/images/pull/634/files

2024-02-15 23:48 UTC, gauravsaini04 commented on src/miniconda/.devcontainer/Dockerfile
> +    pyopenssl==24.0.0
saw compatible versions for `cryptography v42.0.2` on https://pypi.org/project/pyOpenSSL/#section-3
and unavailability of `pyopenssl` required version on https://anaconda.org/search?q=pyopenssl
so, installed with pip

2024-02-16 19:59 UTC, samruddhikhandale requested changes

2024-02-16 19:59 UTC, samruddhikhandale commented on src/miniconda/.devcontainer/Dockerfile
> +    pyopenssl==24.0.0
I see, can you add another test  for `pip` and make sure pip installs continue to work? 

similar to https://github.com/devcontainers/images/blob/e7e4b123bc46bd2f4a265ceb30b8c617c313ec03/src/miniconda/test-project/test.sh#L32-L34

2024-02-16 23:13 UTC, gauravsaini04 commented on src/miniconda/.devcontainer/Dockerfile
> +    pyopenssl==24.0.0
Added tests to check that pip install works in correct manner.

2024-02-16 23:24 UTC, samruddhikhandale approved these changes
Looks good!

2024-02-16 23:24 UTC, merged