miniconda-cryptography-update_for_security_patch_GHSA-6vqw-3v5j-54x4
devcontainers/images pull request #976
Opened 2024-02-27 06:49 UTC by gauravsaini04

**Dev container name**:
 
 * Miniconda
 
 **Description**:
 
 This PR patches the following vulnerability:
 
 * [GHSA-6vqw-3v5j-54x4](https://github.com/advisories/GHSA-6vqw-3v5j-54x4) - related to the `cryptography` package;
 
 This vulnerability comes from the coninuumio/Miniconda3 image used upstream for the Miniconda devcontainer.
 
 _Changelog_:
 
 * Updated Dockerfile
   * Upgraded version for patched python package;
     * `cryptography` - _minimum package version has been set to `42.0.4`_;
   * Removed version for patched conda package;
     * `cryptography` - _minimum package version was previously set to `42.0.2`_;
   * Removed version for patched pyopenssl package;
     * `pyopenssl` - _minimun package version for sake of compatibility with `cryptography v42.02` was previously set to `24.0.0`_;
	 
 * Updated tests to verify `cryptography` minimum version (Minimum package version set to `42.0.4` which fixes [GHSA-6vqw-3v5j-54x4](https://github.com/advisories/GHSA-6vqw-3v5j-54x4));
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-02-27 18:29 UTC, samruddhikhandale requested changes

2024-02-27 18:29 UTC, samruddhikhandale commented on src/miniconda/.devcontainer/Dockerfile
> -    # installed for compatibility with cryptography v42.0.2
> Removed version for patched pyopenssl package;
> pyopenssl - minimun package version for sake of compatibility with cryptography v42.02 was previously set to 24.0.0;

`42.0.4` is an upgrade to the earlier `cryptography` version, hence, won't this be still needed for compat?

2024-02-27 18:29 UTC, samruddhikhandale commented on src/miniconda/test-project/test.sh
> +checkCondaPackageVersion "pyopenssl" "23.2.0"
Deprecating package version doesn't look good, and is unexpected user experience.

At least for this reason, we should keep the patch for `pyopenssl`

2024-02-27 19:00 UTC, gauravsaini04 commented on src/miniconda/test-project/test.sh
> +checkCondaPackageVersion "pyopenssl" "23.2.0"
changed back

2024-02-28 18:51 UTC, samruddhikhandale approved these changes

2024-02-28 18:51 UTC, merged