check size for the universal image
devcontainers/images pull request #979
Opened 2024-02-29 13:41 UTC by prathameshzarkar9

**Dev container name**:
 * universal
 **Description**:
This PR is implementing the following functionality:
 * Github action checks the size of the universal container is exceeding the fixed threshold i.e. 14 GB or not and displays the report with the result success if it is below the threshold and fail if it is beyond the threshold.
 _Changelog_:
 * Updated test.sh
   * if Image is universal then call check_image_size function with two paramteres image and threshold.
  * Created check-image-size.sh
   * This file used to check the image size with the threshold and displays the output pass or fail

 **Checklist**:
 * [x]   Checked that the container has been created and tried to run the github action for the image universal
 * [x]   Successfully checked the size of universal image and displayed report failed as the size exceeded the threshold

2024-02-29 16:24 UTC, prathameshzarkar9 commented
> @prathameshzarkar9 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Infosys"]

2024-03-04 22:59 UTC, samruddhikhandale requested changes

2024-03-04 22:59 UTC, samruddhikhandale commented on src/test-universal/.devcontainer.json
> +{
Why do we need this file?

2024-03-04 22:59 UTC, samruddhikhandale commented on src/test-universal/test-project/test.sh
> +#!/bin/bash
Why do we need this file?

2024-03-04 22:59 UTC, samruddhikhandale commented on .github/actions/smoke-test/test.sh
> +if [ $IMAGE == "test-universal" ]; then
```suggestion
if [ $IMAGE == "universal" ]; then
```

See 👇 https://github.com/devcontainers/images/blob/8d583c121d54f913ea28b3790672b21c52df2a93/.github/workflows/smoke-universal.yaml#L28

2024-03-04 22:59 UTC, samruddhikhandale commented on .github/actions/smoke-test/test.sh
> +    chmod -R 777 $(pwd)/src/$IMAGE/check-size.sh
I don't think we need to add it to /src/universal. 

Can we add `check-size.sh` to https://github.com/devcontainers/images/tree/8d583c121d54f913ea28b3790672b21c52df2a93/.github/actions/smoke-test instead?

2024-03-04 22:59 UTC, samruddhikhandale commented on src/test-universal/check-size.sh
> +gb_value=12.5
```suggestion
gb_value=14
```

Currently, the size is 14 GB, see https://github.com/devcontainers/images/actions/runs/8146012516/job/22263557659#step:3:42668

2024-03-05 04:26 UTC, prathameshzarkar9 commented on src/test-universal/check-size.sh
> +gb_value=12.5
Done

2024-03-05 04:30 UTC, prathameshzarkar9 commented on src/test-universal/.devcontainer.json
> +{
deleted

2024-03-05 04:30 UTC, prathameshzarkar9 commented on src/test-universal/test-project/test.sh
> +#!/bin/bash
deleted

2024-03-05 04:31 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/test.sh
> +if [ $IMAGE == "test-universal" ]; then
done

2024-03-05 09:32 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/test.sh
> +    chmod -R 777 $(pwd)/src/$IMAGE/check-size.sh
done

2024-03-06 18:40 UTC, samruddhikhandale requested changes

2024-03-06 18:40 UTC, samruddhikhandale commented on .github/actions/smoke-test/test.sh
> +    cd $(pwd).github/actions/smoke-test/
Looks like this is failing, see https://github.com/devcontainers/images/actions/runs/8167854903/job/22356629412#step:3:42336

2024-03-07 23:34 UTC, samruddhikhandale requested changes

2024-03-07 23:34 UTC, samruddhikhandale commented on .github/actions/smoke-test/action.yaml
> +    description: 'Threshold size in GB'
```suggestion
    description: 'Image threshold size in GB'
```

2024-03-07 23:34 UTC, samruddhikhandale commented on .github/actions/smoke-test/action.yaml
> +      run: ${{ github.action_path }}/test.sh  ${{ inputs.image }} ${{ inputs.threshold }}
Nice!

2024-03-07 23:34 UTC, samruddhikhandale commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "checking bc is installed.."
Looks like we have failures. See https://github.com/devcontainers/images/actions/runs/8195223860/job/22413000102?pr=979#step:3:42620

2024-03-08 07:53 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "checking bc is installed.."
resolved

2024-03-08 07:57 UTC, prathameshzarkar9 reviewed
@samruddhikhandale ,
requested changes incorporated. Kindly review the same

2024-03-08 19:10 UTC, samruddhikhandale commented on .github/actions/smoke-test/action.yaml
> +    description: 'Threshold in GB to check the image size not excced this limit'
```suggestion
    description: 'Threshold (in GB) to validate that the image size does not exceed this limit'
```

2024-03-08 19:15 UTC, samruddhikhandale commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "in install_bc function.."
Can we remove this?

2024-03-08 19:18 UTC, samruddhikhandale commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "in uninstall_bc function..."
Can we remove this?

2024-03-08 19:19 UTC, samruddhikhandale commented on .github/actions/smoke-test/check-image-size.sh
> +    echo -e "\nThreshold=$threshold"
```suggestion
    echo -e "\nThreshold is $threshold bytes ie $THRESHOLD_IN_GB GB"
```

2024-03-08 19:21 UTC, samruddhikhandale commented on .github/actions/smoke-test/check-image-size.sh
> +uninstall_bc() {
You can cleanup the code for uninstalling `bc` as this is the last operation we perform, and the Action will eventually delete this resource.

2024-03-11 05:47 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/check-image-size.sh
> +uninstall_bc() {
done

2024-03-11 05:48 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/check-image-size.sh
> +    echo -e "\nThreshold=$threshold"
done

2024-03-11 05:48 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "in uninstall_bc function..."
done

2024-03-11 05:48 UTC, prathameshzarkar9 commented on .github/actions/smoke-test/check-image-size.sh
> +    echo "in install_bc function.."
done

2024-03-11 17:28 UTC, samruddhikhandale approved these changes
Looks great, thank you so much! ⚡

2024-03-11 17:28 UTC, merged